config/routes.rb
Rails.application.routes.draw do
  root 'main#index'
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  resources :items do
    member do
      post :plus_rating
      post :minus_rating
    end
  end
  resources :search, only: [:index, :create]
  resources :profiles, only: [:index, :show, :edit, :update]

  namespace :admin do
    get '/', to: 'dashboard#index', as: :dashboard
    resources :categories, except: :show
    resources :subcategories, except: :show
    resources :cities, except: :show
    resources :users, except: :show
  end

  get "/:city", to: "items#city", as: :city
  get "/:city/:category", to: "items#category", as: :category
  get "/:city/:category/:subcategory", to: "items#subcategory", as: :subcategory
  get "/:city/:category/:subcategory/:id", to: "items#show"
end

app/views/inc/admin/_nav.html.erb
<div class="masthead">
  <h3 class="text-muted">Admin.Wenternet</h3>
  <nav>
    <ul class="nav nav-justified">
      <li class="active"><a href="#">Home</a></li>
      <li><a href="#">Projects</a></li>
      <li><a href="#">Services</a></li>
      <li><a href="#">Downloads</a></li>
      <li><a href="#">About</a></li>
      <li><a href="#">Contact</a></li>
    </ul>
  </nav>
</div>

app/views/inc/admin/_sidebar.html.erb
<div id="sidebar-wrapper">
  <ul class="sidebar-nav">
    <li class="sidebar-brand">Menu</li>
    <li>
      <%= link_to "Dashboard", admin_dashboard_path %>
    </li>
    <li>
      <%= link_to "Categories", admin_categories_path %>
    </li>
    <li>
      <%= link_to "Subcategories", admin_subcategories_path %>
    </li>
    <li>
      <%= link_to "Cities", admin_cities_path %>
    </li>
    <li>
      <%= link_to "Users", admin_users_path %>
    </li>
  </ul>
</div>