config/routes.rb
Rails.application.routes.draw do
  root 'main#index'
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  resources :items do
    member do
      post :plus_rating
      post :minus_rating
    end
  end
  resources :search, only: [:index, :create]
  resources :profiles, only: [:index, :show, :edit, :update]

  namespace :admin do
    get '/', to: 'dashboard#index', as: :dashboard
    resources :categories, except: :show
    resources :subcategories, except: :show
    resources :cities, except: :show
    resources :users, except: :show
  end

  get "/:city", to: "items#city", as: :city
  get "/:city/:category", to: "items#category", as: :category
  get "/:city/:category/:subcategory", to: "items#subcategory", as: :subcategory
  get "/:city/:category/:subcategory/:id", to: "items#show"
end

app/models/item.rb
class Item < ActiveRecord::Base
  include AASM

  belongs_to :category
  belongs_to :subcategory
  belongs_to :city
  belongs_to :user
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images

  validates :title,          presence: true, length: { maximum: 255 }
  validates :price,          numericality: { greater_than_or_equal_to: 1 }, allow_nil: true
  validates :category_id,    presence: true
  validates :subcategory_id, presence: true
  validates :city_id,        presence: true
  validates :user_id,        presence: true
  validates :email,          presence: true
  validates :phone,          presence: true

  scope :newest,         -> { order('created_at DESC') }
  scope :published,      -> { where(state: :published) }
  scope :pages,       ->(p) { page(p).per(15) }

  aasm column: :state do
    state :drafted, initial: true
    state :published
    state :expired

    event :publish do
      transitions from: :drafted, to: :published
    end

    event :draft do
      transitions from: :published, to: :drafted
    end

    event :expire do
      transitions from: :published, to: :expired
      transitions from: :drafted,   to: :expired
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  load_and_authorize_resource

  before_action :set_item,   only: [:show, :edit, :update, :destroy, :plus_rating, :minus_rating]
  before_action :set_params, only: [:city, :category, :subcategory]

  def index
    @items = Item.includes(category: :subcategories).includes(:city).pages(params[:page]).all
  end

  def show
    @categories = Category.all
    # TODO: Refactor this
    @recent_items = Item.where(category: @item.category).newest.published.limit(5)
  end

  def new
    @item = Item.new
  end

  def edit; end

  def create
    @item = Item.new(item_params)
    @item.user = current_user
    if @item.save
      unless params[:images].nil?
        params[:images]['attachment'].each do |attch|
          @image = @item.images.create!(attachment: attch)
        end
      end
      redirect_to @item, notice: 'Item was successfully created.'
    else
      render :new
    end
  end

  def update
    if @item.update(item_params)
      unless params[:images].nil?
        @item.images.delete_all
        params[:images]['attachment'].each do |attch|
          @image = @item.images.create!(attachment: attch)
        end
      end
      redirect_to @item, notice: 'Item was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to items_url, notice: 'Item was successfully destroyed.'
  end

  def city
    @items = Item.newest.published.pages(params[:page])
    items_city!
  end

  def category
    @items = Item.newest.published.pages(params[:page]).where(category: @category)
    items_city!
  end

  def subcategory
    @items = Item.where(category: @category, subcategory: @subcategory).newest.published.pages(params[:page])
    items_city!
  end

  def plus_rating
    rate!(1)
  end

  def minus_rating
    rate!(-1)
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def set_params
    @categories  = Category.includes(:subcategories)
    @city        = City.where(uri: params[:city]).first if params[:city]
    @category    = Category.where(uri: params[:category]).first if params[:category]
    @subcategory = Subcategory.where(category: @category,
                                     uri: params[:subcategory]).first if params[:subcategory]
  end

  def items_city!
    @items = @items.where(city: @city) unless all_cities?
  end

  def item_params
    params.require(:item).permit(:title, :price, :content, :category_id, :subcategory_id, :city_id, :user_id,
                                 :email, :phone, :state, images_attributes: [:id, :item_id, :attachment])
  end

  def all_cities?
    @city = 'all' if params[:city].downcase == 'all'
  end

  def rate!(rating)
    if Rating.dublicate?(@item, current_user)
      @message = 'You have already voted'
    else
      @item.user.rate!(@item, current_user, rating)
      @message = 'Your vote has been counted'
    end
  end
end

app/views/items/_breadcrump.html.erb
<br/>
<div class="row">
  <div class="col-sm-12">
    <ol class="breadcrumb">
      <li>
        <% if @city == "all" %>
          <%= link_to "Все города", city_path %>
        <% else %>
          <%= link_to @city.name, city_path(city: @city) %>
        <% end %>
      </li>
      <% unless @category.nil? %>
        <li>
          <%= link_to @category.name, category_path(city: @city, category: @category) %>
        </li>
      <% end %>
      <% unless @subcategory.nil? %>
        <li>
          <%= link_to @subcategory.name, subcategory_path(
                                           city: @city,
                                           category: @category,
                                           subcategory: @subcategory) %>
        </li>
      <% end %>
    </ol>
  </div>
</div>

app/views/items/_form.html.erb
<div class="form-vertical">
  <%= form_for(@item, html: { multipart: true }) do |f| %>
    <%= form_errors @item %>
    <div class="panel panel-default">
      <div class="panel-heading">
        Выберите категорию
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-sm-6">
            <div class="form-group">
              <div class="row">
                <div class="col-sm-3 inline-label">
                  <%= f.label :category_id %>
                </div>
                <div class="col-sm-9">
                  <%= collection_select(:item, :category_id, Category.all, :id, :name, {:include_blank => 'Please Select'}, class: "form-control") %>
                </div>
              </div>
            </div>
          </div>
          <div class="col-sm-6">
            <div class="form-group">
              <div class="row">
                <div class="col-sm-3 inline-label">
                  <%= f.label :subcategory_id %>
                </div>
                <div class="col-sm-9">
                  <%= collection_select(:item, :subcategory_id, Subcategory.all, :id, :name, {:include_blank => 'Please Select'}, class: "form-control") %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        Детали объявления
      </div>
      <div class="panel-body">
        <div class="form-group">
          <div class="row">
            <div class="col-sm-12">
              <%= f.label :title %>
              <%= f.text_field :title, class: "form-control" %>
            </div>
          </div>
        </div>
        <div class="form-group">
          <div class="row">
            <div class="col-sm-12">
              <%= f.label :price %>
              <%= f.text_field :price, class: "form-control" %>
            </div>
          </div>
        </div>
        <div class="form-group">
          <div class="row">
            <div class="col-sm-12">
              <%= f.label :content %>
              <%= f.text_area :content, class: "form-control expand" %>
            </div>
          </div>
        </div>
        <div class="form-group">
          <div class="row">
            <div class="col-sm-12">
              <%= f.label :city_id %><br>
              <%= collection_select(:item, :city_id, City.all, :id, :name, {:include_blank => 'Please Select'}, class: "form-control") %>
            </div>
          </div>
        </div>
        <div class="form-group">
          <label for="item_images">Images</label>
          <%= f.file_field :images, multiple: true, name: 'images[attachment][]' %>
        </div>
        <div class="checkbox">
          <label>
            <%= f.check_box :state, {}, 'published', 'drafted' %> Publish
          </label>
        </div>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        Контактная информация
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-sm-6">
            <div class="form-group">
              <div class="row">
                <div class="col-sm-2 inline-label">
                  <%= f.label :email %>
                </div>
                <div class="col-sm-10">
                  <%= f.text_field :email, class: "form-control" %>
                </div>
              </div>
            </div>
          </div>
          <div class="col-sm-6">
            <div class="form-group">
              <div class="row">
                <div class="col-sm-2 inline-label">
                  <%= f.label :phone %>
                </div>
                <div class="col-sm-10">
                  <%= f.text_field :phone, class: "form-control" %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="actions">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/items/_item_list.html.erb
<div class="row listing-row">
  <span style="">Sort by:&nbsp;&nbsp;&nbsp;</span>
  <a href="#"  data-toggle="tooltip" data-placement="top" title="Sort from newest to oldest"> Date <i class="fa fa-chevron-up"></i></a>
  <a href="#" data-toggle="tooltip" data-placement="top" title="Sort from lowest price to highest price"> Price <i class="fa fa-chevron-down"></i></a>
</div>
<% @items.each do |item| %>
  <div class="row listing-row">
    <div class="col-sm-2">
      <% unless item.images.first.nil? %>
        <%= link_to image_tag(item.images.first.attachment.preview.url), item_path(item), class: "thumbnail" %>
      <% end %>
    </div>
    <div class="col-sm-10">
      <h3>
        <%= link_to(item_path(item)) do %>
          <%= item.title %> - <strong><%= item.price %></strong>
        <% end %>
      </h3>
      <p class="muted">Город <strong><%= item.city.name %></strong></p>
      <p class="muted">Размещено <%= item.created_at.strftime("%d %B %Y")%>
        в разделе <%= link_to item.subcategory.name, subcategory_path(
                                                       city: item.city,
                                                       category:item.category,
                                                       subcategory: item.subcategory) %></p>
      <br/>
      <p><%= item.content %></p>
      <br/>
      <p>
                          <span class="classified_links">
                            <%= link_to "Посмотреть полностью", item_path(item), class: "link-info underline" %> |
                            <%= link_to "Добавить в избарнное", "#", class: "link-info underline" %>
                          </span>
      </p>
    </div>
  </div>
<% end %>
<%= paginate @items %>

app/views/items/_jumbotron_search.html.erb
<div class="jumbotron home-tron-search well">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <div class="home-tron-search-inner">
          <%= form_tag(controller: 'search', action: 'create', method: 'post') do %>
            <div class="row">
              <div class="col-sm-8 col-xs-9" style="text-align: center">
                <div class="row">
                  <div class="col-sm-12 col-sm-offset-1">
                    <div class="input-group">
                      <span class="input-group-addon input-group-addon-text">Нужно найти</span>
                      <%= text_field_tag("search[query]", nil,
                                         placeholder: "e.g. BMW, 2 bed flat, sofa ",
                                         class: 'form-control') %>
                      <div class=" input-group-addon hidden-xs">
                        <%= collection_select(:search, :category, @categories, :id, :name,
                                              { prompt: "Все категории" },
                                              { class: "form-control search_options" }) %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-sm-4 col-xs-3" style="text-align: center">
                <div class="row">
                  <div class="col-sm-11 pull-right">
                    <%= submit_tag("Поиск", class: "btn btn-primary search-btn") %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/items/category.html.erb
<%= render "jumbotron_search" %>

<div class="container">
  <%= render "breadcrump" %>

  <div class="row">
    <div class="col-sm-3 hidden-xs">
      <div class="sidebar">
        <div class="panel panel-default">
          <div class="panel-heading">Список подкатегорий</div>
          <ul class="list-group">
            <% @category.subcategories.each do |subcategory| %>
              <li class="list-group-item"><%= link_to subcategory.name, subcategory_path(
                                                                       city: @city,
                                                                       category: @category,
                                                                       subcategory: subcategory) %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <div class="col-sm-9 pull-right listings">
      <%= render "item_list" %>
    </div>
  </div>
</div>

app/views/items/city.html.erb
<%= render "jumbotron_search" %>

<div class="container">
  <%= render "breadcrump" %>

  <div class="row">
    <div class="col-sm-3 hidden-xs">
      <div class="sidebar">
        <div class="panel panel-default">
          <div class="panel-heading">Список категорий</div>
          <ul class="list-group">
            <% @categories.each do |category| %>
              <li class="list-group-item"><%= link_to category.name, category_path(
                                                                       city: @city,
                                                                       category: category) %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <div class="col-sm-9 pull-right listings">
      <%= render "item_list" %>
    </div>
  </div>
</div>

app/views/items/edit.html.erb
<hr class="topbar">
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<h1>Listing Items</h1>

<% if can? :new, Item %>
  <%= link_to 'New Item', new_item_path %>
<% end %>
<table class="table table-hover table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Price</th>
      <th>Content</th>
      <th>Category</th>
      <th>Subcategory</th>
      <th>City</th>
      <th>User</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Status</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= link_to item.title, item %></td>
        <td><%= item.price %></td>
        <td><%= item.content %></td>
        <td><%= link_to item.category.name, category_path(city: item.city, category: item.category) %></td>
        <td><%= link_to item.subcategory.name, subcategory_path(city: item.city, category: item.category, subcategory: item.subcategory) %></td>
        <td><%= link_to item.city.name, city_path(item.city) %></td>
        <td><%= item.user.name %></td>
        <td><%= item.email %></td>
        <td><%= item.phone %></td>
        <td><%= item.state.capitalize %></td>
        <% if can? :edit, item %>
          <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <% end %>
        <% if can? :destroy, item %>
          <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @items %>

app/views/items/new.html.erb
<hr class="topbar">
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/items/show.html.erb
<%= render "jumbotron_search" %>

<div class="container" id="listings-page">
  <div class="row">
    <div class="col-sm-12 listing-wrapper listings-top listings-bottom">
      <br/>
      <div class="row">
        <div class="col-sm-7">
          <ol class="breadcrumb">
            <li>
              <%= link_to @item.city.name, city_path(city: @item.city) %>
            </li>
            <li>
              <%= link_to @item.category.name, category_path(city: @item.city, category: @item.category) %>
            </li>
            <li>
              <%= link_to @item.subcategory.name, subcategory_path(
                                                      city: @item.city,
                                                      category: @item.category,
                                                      subcategory: @item.subcategory) %>
            </li>
          </ol>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-7">
          <h1><%= @item.title %></h1>
        </div>
        <div class="col-sm-5">
          <p class="price"><%= @item.price %></p>
        </div>
      </div>
      <hr/>
      <div class="row">
        <div class="col-sm-7">
          <h3>Детали</h3>
          <div class="row">
            <div class="col-xs-6">
              <table class="table">
                <tbody>
                  <tr>
                    <th>Автор</th>
                    <td><%= link_to @item.user.name, profile_path(@item.user) %></td>
                  </tr>
                  <tr>
                    <th>Телефон</th>
                    <td><%= @item.phone %></td>
                  </tr>
                  <tr>
                    <th>Email</th>
                    <td><%= @item.email %></td>
                  </tr>
                </tbody>
              </table>
            </div>
            <div class="col-xs-6">
              <table class="table">
                <tbody>
                  <tr>
                    <th>Размещено</th>
                    <td><%= @item.created_at.strftime("%d %B %Y")%></td>
                  </tr>
                  <tr>
                    <th>Город</th>
                    <td><%= link_to @item.city.name, city_path(city: @item.city) %></td>
                  </tr>
                </tbody>
              </table>
            </div>
            <div class="col-xs-12">
              <h3>Описание</h3>
              <p><%= @item.content %></p>
              <p>
                <span class="classified_links ">
                  <% if can? :edit, @item %>
                    <a href="#" class="link-info">Редактировать объявление</a> |
                  <% end %>
                  <% if can? :vote, @item %>
                    <a class="plus-rating link-info" href="#" data-url=<%= plus_rating_item_path(@item) %>>+</a> |
                    <a class="minus-rating link-info" href="#" data-url=<%= minus_rating_item_path(@item) %>>-</a> |
                    <a class="minus-rating link-info" href="#" data-url=<%= minus_rating_item_path(@item) %>>Добавить в избранное</a>
                  <% end %>
                </span>
              </p>
            </div>
          </div>
        </div>
        <div class="col-sm-5 center zoom-gallery">
          <div class="row">
            <div class="center">
              <div class="col-sm-12">
                <div class="gallery-preview">
                  <% @item.images.each do |img| %>
                    <%= link_to image_tag(img.attachment.preview.url), img.attachment.url, class: "thumbnail" %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <hr/>
      <div class="col-sm-12 listings">
        <br/>
        <div class="row">
          <div class="panel panel-default recent-listings hidden-xs">
            <div class="panel-heading">
              Последние объявления в разделе "<%= @item.category.name %>"
            </div>
            <div class="panel-body">
              <% @recent_items.each do |item| %>
                <div class="row listing-row">
                  <div class="col-sm-2">
                    <% unless item.images.first.nil? %>
                      <%= link_to image_tag(item.images.first.attachment.preview.url), item_path(item), class: "thumbnail" %>
                    <% end %>
                  </div>
                  <div class="col-sm-10">
                    <div class="row">
                      <div class="col-sm-9">
                        <h3><%= link_to item.title, item_path(item) %></h3>
                      </div>
                      <div class="col-sm-3">
                        <h3 class="price-text"><strong><%= item.price %></strong></h3>
                      </div>
                    </div>

                    <div class="row">
                      <div class="col-sm-12">
                        <p class="muted">Город <%= item.city.name %></strong></p>
                        <p class="muted">Размещено <%= item.created_at.strftime("%d %B %Y")%>
                          в разделе <%= link_to item.subcategory.name, subcategory_path(
                                                                   city: item.city,
                                                                   category:item.category,
                                                                   subcategory: item.subcategory) %></p>
                        <br/>
                        <p><%= item.content %></p>
                        <br/>
                      </div>
                    </div>
                  </div>
                  <div class="col-sm-12">
                    <div class="row">
                      <div class="col-sm-2"></div>
                      <div class="col-sm-10">
                        <p>
                          <span class="classified_links">
                            <%= link_to "Посмотреть полностью", item_path(item), class: "link-info underline" %> |
                            <%= link_to "Добавить в избарнное", "#", class: "link-info underline" %>
                          </span>
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/items/subcategory.html.erb
<%= render "jumbotron_search" %>

<div class="container">
  <%= render "breadcrump" %>
  <div class="row">
    <div class="col-sm-3 hidden-xs">
      <div class="sidebar">
        <div class="panel panel-default">
          <div class="panel-heading">Список подкатегорий</div>
          <ul class="list-group">
            <% @category.subcategories.each do |subcategory| %>
              <li class="list-group-item <%= 'selected' if subcategory == @subcategory  %>">
                <%= link_to subcategory.name, subcategory_path(city: @city,
                                                               category: @category,
                                                               subcategory: subcategory) %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <div class="col-sm-9 pull-right listings">
      <%= render "item_list" %>
    </div>
  </div>
</div>